export const BASE_URL = "http://37.44.244.196:7777"
export const BASE_URL_INDOAREA = "https://dev.farizdotid.com/api/daerahindonesia"

export const PROCESS_FETCH_LOCATION_TYPE = "PROCESS_FETCH_LOCATION_TYPE"
export const SUCCESS_FETCH_LOCATION_TYPE = "SUCCESS_FETCH_LOCATION_TYPE"
export const FAILED_FETCH_LOCATION_TYPE = "FAIELD_FETCH_LOCATION_TYPE"

export const PROCESS_FETCH_PROVINSI = "PROCESS_FETCH_PROVINSI"
export const SUCCESS_FETCH_PROVINSI = "SUCCESS_FETCH_PROVINSI"
export const FAILED_FETCH_PROVINSI = "FAILED_FETCH_PROVINSI"

export const PROCESS_FETCH_CITY = "PROCESS_FETCH_CITY"
export const SUCCESS_FETCH_CITY = "SUCCESS_FETCH_CITY"
export const FAILED_FETCH_CITY = "FAILED_FETCH_CITY"
