export const BASE_URL = "http://127.0.0.1/dev/api";
export const BASE_URL_INDOAREA =
  "https://dev.farizdotid.com/api/daerahindonesia";

export const BASE_URL_SOCKET_SERVICE_STREAM = "ws://127.0.0.1:8887";
export const BASE_URL_SSE_SERVICE_STREAM = "http://127.0.0.1:8887";

export const PROCESS_FETCH_LOCATION_TYPE = "PROCESS_FETCH_LOCATION_TYPE";
export const SUCCESS_FETCH_LOCATION_TYPE = "SUCCESS_FETCH_LOCATION_TYPE";
export const FAILED_FETCH_LOCATION_TYPE = "FAIELD_FETCH_LOCATION_TYPE";

export const PROCESS_FETCH_PROVINSI = "PROCESS_FETCH_PROVINSI";
export const SUCCESS_FETCH_PROVINSI = "SUCCESS_FETCH_PROVINSI";
export const FAILED_FETCH_PROVINSI = "FAILED_FETCH_PROVINSI";

export const PROCESS_FETCH_CITY = "PROCESS_FETCH_CITY";
export const SUCCESS_FETCH_CITY = "SUCCESS_FETCH_CITY";
export const FAILED_FETCH_CITY = "FAILED_FETCH_CITY";

// dashboar data
export const PROCESS_FETCH_LOCATIONS = "PROCESS_FETCH_LOCATIONS";
export const SUCCESS_FETCH_LOCATIONS = "SUCCESS_FETCH_LOCATIONS";
export const FAILED_FETCH_LOCATIONS = "FAILED_FETCH_LOCATIONS";

// counter bar
export const PROCESS_FETCH_COUNTER = "PROCESS_FETCH_COUNTER";
export const SUCCESS_FETCH_COUNTER = "SUCCESS_FETCH_COUNTER";
export const FAILED_FETCH_COUNTER = "SUCCESS_FETCH_COUNTER";

// fetch get location by id
export const PROCESS_FETCH_LOCATIONS_ID = "PROCESS_FETCH_LOCATIONS_ID";
export const SUCCESS_FETCH_LOCATIONS_ID = "SUCCESS_FETCH_LOCATIONS_ID";
export const FAILED_FETCH_LOCATIONS_ID = "FAILED_FETCH_LOCATIONS_ID";

// fetch get nearby place...
export const PROCESS_GET_NEARBY_LOCATIONS = "PROCESS_GET_NEARBY_LOCATIONS";
export const SUCCESS_GET_NEARBY_LOCATIONS = "SUCCESS_GET_NEARBY_LOCATIONS";
export const FAILED_GET_NEARBY_LOCATIONS = "FAILED_GET_NEARBY_LOCATIONS";

export const PROCESS_ADD_LOCATION = "PROCESS_ADD_LOCATION";
export const SUCCESS_ADD_LOCATION = "SUCCESS_ADD_LOCATION";
export const FAILED_ADD_LOCATIONS = "FAILED_ADD_LOCATIONS";

export const PROCESS_FETCH_GEOFENCE_BY_TYPE = "PROCESS_FETCH_GEOFENCE_BY_TYPE";
export const SUCCESS_FETCH_GEOFENCE_BY_TYPE = "SUCCESS_FETCH_GEOFENCE_BY_TYPE";
export const FAILED_FETCH_GEOFENCE_BY_TYPE = "FAILED_FETCH_GEOFENCE_BY_TYPE";

export const PROCESS_FETCH_AVG_DETECT_BY_AREA =
  "PROCESS_FETCH_AVG_DETECT_BY_AREA";
export const SUCCESS_FETCH_AVG_DETECT_BY_AREA =
  "SUCCESS_FETCH_AVG_DETECT_BY_AREA";
export const FAILED_FETCH_AVG_DETECT_BY_AREA =
  "FAILED_FETCH_AVG_DETECT_BY_AREA";

export const PROCESS_ADD_GEOFENCE_AREA =
  "PROCESS_ADD_GEOFENCE_AREA";
export const SUCCESS_ADD_GEOFENCE_AREA =
  "SUCCESS_ADD_GEOFENCE_AREA";
export const FAILED_ADD_GEOFENCE_AREA =
  "FAILED_ADD_GEOFENCE_AREA";
